export interface MockIncident {
  id: string;
  title: string;
  severity: "P1" | "P2" | "P3" | "P4";
  services: string[];
  occurredAt: string;
  resolvedAt: string;
  durationMinutes: number;
  rootCause: string;
  resolution: string;
  preventionNotes: string;
}

export const mockIncidents: MockIncident[] = [
  {
    id: "inc-001",
    title: "payment-service 8% error rate — checkout broken",
    severity: "P1",
    services: ["payment-service", "api-gateway"],
    occurredAt: "2024-01-10T14:31:00Z",
    resolvedAt: "2024-01-10T15:05:00Z",
    durationMinutes: 34,
    rootCause: "Deploy v2.3.9 introduced null dereference in PaymentProcessor when Stripe SCA flag was enabled but provider config was missing",
    resolution: "Rolled back to v2.3.8 via kubectl rollout undo; error rate returned to baseline within 3 minutes",
    preventionNotes: "Add integration test covering SCA code path with incomplete config; add config validation on startup",
  },
  {
    id: "inc-002",
    title: "auth-service OOMKilled — login unavailable for 22 minutes",
    severity: "P1",
    services: ["auth-service", "api-gateway"],
    occurredAt: "2024-01-08T03:14:00Z",
    resolvedAt: "2024-01-08T03:36:00Z",
    durationMinutes: 22,
    rootCause: "Memory leak in JWT validation library v2.3.1 — unbounded cache for parsed token claims with no eviction",
    resolution: "Rolled back JWT library to v2.2.9; increased pod memory limit from 512Mi to 768Mi as buffer",
    preventionNotes: "Pin library versions in lock file; add memory trend alert at 80% utilization",
  },
  {
    id: "inc-003",
    title: "inventory-service unavailable — connection pool exhausted",
    severity: "P2",
    services: ["inventory-service", "order-service", "inventory-db"],
    occurredAt: "2024-01-07T09:22:00Z",
    resolvedAt: "2024-01-07T09:58:00Z",
    durationMinutes: 36,
    rootCause: "Flash sale traffic 4x normal; connection pool max (100) exhausted; no connection pooler in place",
    resolution: "Killed idle connections, increased pool to 200, restarted pods; deployed PgBouncer in transaction mode the following day",
    preventionNotes: "Deploy PgBouncer before next sale event; add connection wait time alert at 500ms",
  },
  {
    id: "inc-004",
    title: "fraud-model-svc p99 latency > 30s — payments delayed",
    severity: "P2",
    services: ["fraud-model-svc", "fraud-service", "payment-service"],
    occurredAt: "2024-01-05T16:45:00Z",
    resolvedAt: "2024-01-05T17:30:00Z",
    durationMinutes: 45,
    rootCause: "Missing composite index on (feature_name, model_version) in ml-feature-store; table scan on 200M rows",
    resolution: "Added index CONCURRENTLY; latency dropped to 45ms within 10 minutes of index build completing",
    preventionNotes: "Add slow query alert; review query plans in staging before shipping data migrations",
  },
  {
    id: "inc-005",
    title: "order-service deadlocks during flash sale",
    severity: "P2",
    services: ["order-service", "order-db"],
    occurredAt: "2024-01-03T12:00:00Z",
    resolvedAt: "2024-01-03T12:48:00Z",
    durationMinutes: 48,
    rootCause: "Concurrent writes to orders table acquiring row locks in inconsistent order; deadlock cycle between order creation and status update",
    resolution: "Added SELECT FOR UPDATE SKIP LOCKED; implemented retry with exponential backoff on deadlock error",
    preventionNotes: "Load test concurrent write patterns before high-traffic events",
  },
  {
    id: "inc-006",
    title: "api-gateway TLS certificate expired",
    severity: "P1",
    services: ["api-gateway"],
    occurredAt: "2023-12-31T00:00:00Z",
    resolvedAt: "2023-12-31T00:38:00Z",
    durationMinutes: 38,
    rootCause: "cert-manager auto-renewal cron job silently failed due to IAM permission change 30 days prior; no monitoring on cert expiry",
    resolution: "Manually renewed cert via Let's Encrypt; fixed IAM role; added cert expiry alert at 30 and 7 days",
    preventionNotes: "Monitor certificate expiry across all ingresses; test cert renewal in staging",
  },
  {
    id: "inc-007",
    title: "fraud-service false positive surge — 12% legit payments blocked",
    severity: "P2",
    services: ["fraud-service", "fraud-model-svc"],
    occurredAt: "2023-12-28T10:00:00Z",
    resolvedAt: "2023-12-28T13:30:00Z",
    durationMinutes: 210,
    rootCause: "Model retrain with new geographic data introduced bias; threshold not adjusted post-retrain; no A/B shadow mode",
    resolution: "Rolled back to previous model version; reprocessed affected transactions; refunded incorrectly declined orders",
    preventionNotes: "Require shadow mode evaluation for 24h before promoting model to production; monitor precision/recall in production",
  },
  {
    id: "inc-008",
    title: "payment-service duplicate charges after network partition",
    severity: "P2",
    services: ["payment-service", "payment-db"],
    occurredAt: "2023-12-20T18:30:00Z",
    resolvedAt: "2023-12-20T19:15:00Z",
    durationMinutes: 45,
    rootCause: "Network partition between payment-service and payment-db; service retried after timeout without idempotency check; payment-db lacked UNIQUE constraint on idempotency_key",
    resolution: "Added UNIQUE constraint on idempotency_key; fixed retry logic to check for existing charge before retrying; refunded 23 duplicate charges",
    preventionNotes: "Idempotency keys required on all payment mutations; add constraint in DB not just application layer",
  },
  {
    id: "inc-009",
    title: "notification-service email backlog — 2h delivery delay",
    severity: "P3",
    services: ["notification-service", "email-service"],
    occurredAt: "2023-12-15T11:00:00Z",
    resolvedAt: "2023-12-15T13:10:00Z",
    durationMinutes: 130,
    rootCause: "Marketing blast sent 500k emails simultaneously; SendGrid rate limit hit; no backpressure or queue depth monitoring",
    resolution: "Implemented rate-limited queue with 1000 emails/min cap; added dead-letter queue; upgraded SendGrid plan",
    preventionNotes: "All bulk email jobs must use rate-limited queue; add queue depth alert at 10k messages",
  },
  {
    id: "inc-010",
    title: "inventory-service stale stock counts — overselling",
    severity: "P3",
    services: ["inventory-service", "redis-cache", "inventory-db"],
    occurredAt: "2023-12-10T09:00:00Z",
    resolvedAt: "2023-12-10T09:45:00Z",
    durationMinutes: 45,
    rootCause: "Redis cache TTL set to 1 hour; inventory DB writes did not invalidate cache; flash sale depleted stock but cache showed items available",
    resolution: "Reduced TTL to 5 minutes; added cache invalidation on every inventory write; cleared stale cache keys",
    preventionNotes: "Cache TTL must be appropriate to data freshness requirements; write-through or invalidate-on-write pattern required for inventory",
  },
];
